### ISSUE TITLE
"PoshBot.GChat.Backend.psm1" missing from Module

### ISSUE THREAD

**Issue by phatmandrake** [scrthq/PoshBot.GChat.Backend#1] opened 2019-03-15 18:15 UTC
"PoshBot.GChat.Backend.psm1" seems to be missing since the Aug 16, 2018 Commit, which is causing Import-Module to fail.

**Comment by scrthq** [comment] 2019-03-15 18:56
Oh wow, seeing that! Thanks for pointing that out, @phatmandrake! Getting that fixed by tonight!

**Comment by scrthq** [comment] 2019-03-19 12:08
Alright, so after digging through, the issue isn't that the PSM1 is missing from the repo, it's that the CI build and deploy deployed the working directory to the PowerShell Gallery and not the module compiled during the build.

Here's the `psake` task that compiles the module during the CI build:

https://github.com/scrthq/PoshBot.GChat.Backend/blob/master/psake.ps1#L111..L140

If you clone this repo locally then run `build.ps1`, you'll see a new folder generated in the root of the repo named `out` which contains the compiled module in it.


Working on updating the deployment task on the build script once I have a second! Building it locally will get you going for now though, at least =]

**Closed as completed** 2019-03-19 12:12 UTC
Labels: bug

**Comment by scrthq** [comment] 2019-03-19 12:16
New version building now that should fix this =]

**Comment by scrthq** [comment] 2019-03-19 12:23
![image](https://user-images.githubusercontent.com/12724445/54605674-cd440100-4a17-11e9-9ba8-1288ff630a8c.png)

Fixed and available on the [Gallery](https://www.powershellgallery.com/packages/PoshBot.GChat.Backend/0.2.3) now!

**Comment by phatmandrake** [comment] 2019-03-19 14:01
Excellent! I was able to get around it by using the .psm1 I found on the 16th, thanks for fixing this!

**Comment by scrthq** [comment] 2019-03-19 14:12
You bet! Thanks for bringing it to my attention!
